server:
  port: 8081
  servlet-path: /
spring:
  dubbo:
    application:
      id: provider_service
      name: provider_service
      owner: mingxiangjun
    registry:
      address: zookeeper://ming:2181
    consumer:
      group: debug
      version: 1.0.0
    provider:
      group: debug
      version: 1.0.0
    protocol:
      name: dubbo
      port: 20880
  kafka:
    bootstrap-servers: 192.168.1.102:9092
    consumer:
      group-id: default
      key-deserializer: